# Generated by Django 5.1.1 on 2024-12-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_domestictour_slug_internationaltour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationaltour',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.region'),
        ),
    ]
