# Generated by Django 5.1.1 on 2025-02-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tours', '0003_alter_internationaltour_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('home', 'Ana Sayfa'), ('domestic', 'Yurt İçi Turlar'), ('international', 'Yurt Dışı Turlar'), ('contact', 'İletişim'), ('about', 'Hakkımızda')], default='home', max_length=20),
        ),
        migrations.CreateModel(
            name='FeaturedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('internationaltour', 'domestictour')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Öne Çıkan Tur',
                'verbose_name_plural': 'Öne Çıkan Turlar',
                'ordering': ['order'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
