# Generated by Django 5.1.1 on 2025-02-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_banner_type_featuredtour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedTour',
        ),
    ]
